name = "idealista-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "idealista-tracker-db"
database_id = "PLACEHOLDER"

[vars]
ALLOWED_ORIGIN = "https://lmvfa.github.io"
